# NumPy Arrays

**python objects:**
    
1. High-level number objects: integers, floting point
2. containers: lists ( costless instertion and append), dictionaries (fast lookup)

**Numpy Provides:**
    
1. extension package to python for multi-dimentional arrays
2. closer to hardware (efficiency)
3. designed for scientfic computation (convenience)
4. Also known as array oriented computing.

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


**why it is useful : memory-efficient container that provides fast numerical operations**

In [2]:
# python lists

l = range(1000)
%timeit [i**2 for i in l]

761 µs ± 85 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
a = np.array(1000)
%timeit a**2

1.49 µs ± 96.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Creating arrays

**1.1  Manual Construction of arrays**

In [4]:
a = np.array([1,2,3]) 
print (a)

[1 2 3]


In [5]:
# print dimentions
a.ndim

1

In [6]:
# shape
a.shape

(3,)

In [7]:
# 2=D, 3-D

b = np.array([[1, 2], [3, 4]]) 
print (b)

[[1 2]
 [3 4]]


In [8]:
b.ndim

2

In [9]:
b.shape

(2, 2)

In [10]:
len(b)   # return the size of the first dimentions

2

In [11]:
# 3-D Dimentions
c = np.array([[[1, 2], [3, 4]], [[4,5], [6,7]]])  

c

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [12]:
c.ndim

3

In [13]:
c.shape

(2, 2, 2)

**1.2 Function for creating arrays**

In [14]:
# using arrange function

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b = np.arange(1,10,2)  # start, end, step
b

array([1, 3, 5, 7, 9])

In [16]:
# using linspace

a = np.linspace(0,1,6)   # start, end, step
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
# common arrays

a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
c = np.eye(3, 2)  # return 2-D array with ones on the diagonal and zeros else

c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [20]:
# create array using diag function

a = np.diag([1, 2, 3, 4])  # construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
 np.diag(a)  #extract diagonal

array([1, 2, 3, 4])

In [22]:
# create array using random

# create an array of the given shape and populate it with random sample 

a = np.random.rand(4)

a

array([0.03377894, 0.73723623, 0.41977113, 0.79402638])

In [23]:
a = np.random.randn(4)

a

array([-1.54001142,  0.27552436, -0.06240028,  1.853742  ])

**Note:**

# 2. Basic Data Types

In [24]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a.dtype

dtype('int32')

In [26]:
# you can explicitly specify which data-type you want :

a = np.arange(10, dtype = 'float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
a = np.zeros((3,3))   # the default data type is float for zeros and ones function.
print(a)

print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# Other Datatypes

In [28]:
d = np.array([1+2j, 2+4j])  # Complex datatype

print(d.dtype)

complex128


In [29]:
b = np.array([True, False, True, False])  # Boolean datatype

print(b.dtype)

bool


In [30]:
s = np.array(['Ram', 'robert', 'Rahim'])

s.dtype

dtype('<U6')

**Each built-in data type has a character code that uniquely identifiers it.**

# 3. Indexing and slicing

**Indexing**

In [31]:
a = np.arange(10)
print(a[5])   # indicates begin at 0, like other oython sequences (and c/c++)

5


In [32]:
# for multidimentional arrays, indexes are tuples of integers : 
a = np.diag([1, 2, 3])

print([2,2])

[2, 2]


In [33]:
a[2,1] = 5  # assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**Slicing**

In [34]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[1:8:2]   # [ startindex : endindex : step]

array([1, 3, 5, 7])

In [36]:
# we can also combine assignment and slicing

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [37]:
b = np.arange(5)
a[5:] = b[::-1]  # assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in momery. you can use np.may_share_memory() to check if two arrays share the same memory block.

When modifying the view, the original array is modifiedd as well.

In [38]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [40]:
np.shares_memory(a,b)

True

In [41]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [42]:
a  # eventhough we modified b, it update 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [43]:
a = np.arange(10)

c = a[::2].copy()

c

array([0, 2, 4, 6, 8])

In [44]:
np.shares_memory(a,c)

False

In [45]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Fancy Indexing

**Numpy arrays cen be indexed with slices, but also with boolean or Integer arrays (masks). This method is called fancy Indexing. it creates copies not views.

**Using Boolean Mask**

In [46]:
a = np.random.randint(0, 20, 15)
a

array([ 8,  5, 10,  7,  1,  3,  8,  3,  0,  4,  3,  0, 15,  7,  9])

In [47]:
mask = (a % 2 == 0)

In [48]:
extract_from_a = a[mask]

extract_from_a

array([ 8, 10,  8,  0,  4,  0])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [49]:
a[mask] = -1
a

array([-1,  5, -1,  7,  1,  3, -1,  3, -1, -1,  3, -1, 15,  7,  9])

**Indexing with an array of integers**

In [50]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [52]:
# new values can be assigned

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])